# Generated by Django 3.2.24 on 2024-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHHH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hHHH', models.BigIntegerField()),
            ],
        ),
    ]
